### ISSUE TITLE
speedtest.net

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#620]
http://beta.speedtest.net/

Start the Test!

![1](https://user-images.githubusercontent.com/31142317/31034311-cbcc3c3e-a563-11e7-8b35-390fad19ddfe.png)
![2](https://user-images.githubusercontent.com/31142317/31034312-cbf32876-a563-11e7-854c-59d7a07c0a14.png)

**Comment by jspenguin2017** [comment]
Looks like a bad filter from EasyList. 
`|http://$xmlhttprequest,domain=speedtest.net,badfilter`

**Comment by gotitbro** [comment]
@jspenguin2017 That is not a badfilter! Speedtest does serve ads that way on speedtest.net. This issue has been fixed in uBlock filters so please remove the filter.

**Comment by uBlock-user** [comment]
`speedtest.net##script:inject(abort-on-property-read.js, _sp_)`

It's SourcePoint anti adblock script, and uBlock's filter doesn't fix it, I can still reproduce it sometimes.

**Comment by jspenguin2017** [comment]
@uBlock-user Can't reproduce, it works fine for me.

**Comment by hawkeye116477** [comment]
It has been fixed 3 hours ago https://github.com/uBlockOrigin/uAssets/commit/d50f7d34f782089e9855d3ef6f25cbe9a9bd2a6a.

**Comment by gotitbro** [comment]
@uBlock-user There is not point in stopping the anti adblock notice if the speed test isn't gonna work. An EasyList filter was breaking the speedtest which has now been fixed with even better filters in uBO.
