### ISSUE TITLE
kickassanime.ru

### ISSUE THREAD

**Issue by blackholeearth** [jspenguin2017/uBlockProtector#893]
### Test link (required): 
www.kickassanime.ru/anime/25-sai-no-joshikousei-uncensored/episode-02

### Screenshot of the web page (including address bar and extension icons) (required): 

https://imgur.com/a/iHiWT

### Screenshot of the console (press `F12` to bring up the console) (required): 

https://imgur.com/a/fNOtj

### Explain what was not right (optional if obvious): 
ads showing. :  they may be related to   mgid   steep.to

### Reproduction steps (optional if trivial): 
just open page and wait 

### Environment (Required): 

- Operating System and Version:  win10
- Browser and Version:  Google Chrome 65.0.3325.181 (64 bit) 
- Adblocker and Version:  Nano Adblocker 1.0.0.37

#### Your filter lists (Required): 

i have default list +  
i enabled   fdefender integration at the top of filter list.

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.

**Comment by blackholeearth** [comment]
hi, you say fixed, but it still show up.  i updated filters. from control panel. 

is there anything else i need to do (to get that new  filters)??
if yes:
 it would be good for other users  to know what to do to get new  filters.(adding them right below to template thing would be nice )

sorry for bothering

**Comment by jspenguin2017** [comment]
It will update automatically, you can invalidate the cache manually to make it happen sooner.
