### ISSUE TITLE
whiskyprices.co.uk

### ISSUE THREAD

**Issue by Shinzawaii** [jspenguin2017/uBlockProtector#894]
Test link (required):  E.g. anything when you search for something on the site and want to see the prices: https://whiskyprices.co.uk/whisky/glengoyne-18-year-old

Screenshot message:
https://i.imgur.com/q4gqSEQ.png

Console:
https://i.imgur.com/UE3aHpL.png

If you search for anything on the site and scroll down to look at the actual prices (of the price comparer) they won't show but instead give you the ad block detected error.

Windows 10 - up to date
Google chrome - up to date

Filter lists enabled:
- ublock filters
- adblock warning removal list
- easylist
- easyprivacy
- malware domains
- peter lowe ad and tracking server list

Custom filters:
Only those in your instructions.

**Comment by okiehsch** [comment]
Fixed.

**Comment by Shinzawaii** [comment]
Thanks for the very fast response and fix, however I still get the same error, is that possibily due to interference with any of the 'standard' ublock origin lists enabled (see above)?

**Comment by Shinzawaii** [comment]
Cfr. above, I've tried it with all other extensions disabled except for uorigin and nanodefender and still have the same error message.

**Comment by jspenguin2017** [comment]
It works for me, make sure to update your filters. 
![image](https://user-images.githubusercontent.com/7283682/37975529-caa7a81e-319c-11e8-8605-7f187e0d60c6.png)

**Comment by Shinzawaii** [comment]
I see what happened, it works for me on whiskyprices.co.uk as well, but I checked another one of their other URLs (which redirects to the same site basically); whiskyprijzen.nl, whiskyprijzen.be, whiskypreisvergleich.de etc. which is apparently 'not fixed'. 

Not an issue for me though, but there isn't a simple way for me to manually add them to the filter is there?

Once more, thanks again for the quick reply and the fix/update!

**Comment by jspenguin2017** [comment]
Can you provide a test link for each of their domain?

**Comment by Shinzawaii** [comment]
Sure;
[](https://whiskyprijzen.com/) redirects to [](https://whiskyprijzen.nl/)
Then there's also [](https://whiskyprijzen.be/), [](https://whiskypreisvergleich.de/), [](https://whiskyprix.fr/) and [](https://whiskyprix.be/) as domain names redirecting to the same site.

**Comment by okiehsch** [comment]
Does
````
whiskypreisvergleich.de,whiskyprices.co.uk,whiskyprijzen.be,whiskyprijzen.nl,whiskyprix.be,whiskyprix.fr##.blocker
@@*$generichide,domain=whiskypreisvergleich.de|whiskyprices.co.uk|whiskyprijzen.be|whiskyprijzen.nl|whiskyprix.be|whiskyprix.fr
````
fix all "whisky" sites?

**Comment by Shinzawaii** [comment]
Do I have to add that? I've just updated the ublock origin 3th party filters and the only one that works (i.e. doesn't detect adblocker anymore) is whiskyprices.co.uk currently. It still detects ad blocker on the other domains mentioned above.

**Comment by okiehsch** [comment]
I have not added the filter yet.
I wanted to know if
````
whiskypreisvergleich.de,whiskyprices.co.uk,whiskyprijzen.be,whiskyprijzen.nl,whiskyprix.be,whiskyprix.fr
````
are all whisky-domains, or if there are more.

**Comment by Shinzawaii** [comment]
@okiehsch you can add [](whiskyprijzen.com) which seems to redirect to their .nl domain (seems the 'default' domain) but other than yes those are all URLs/domains.
Thanks in advance.
