### ISSUE TITLE
9anime.is

### ISSUE THREAD

**Issue by xnieatx** [jspenguin2017/uBlockProtector#914]
### Test link (required): 

https://www4.9anime.is/watch/tokyo-ghoulre.2yx0/13608p

### Screenshot of the web page (including address bar and extension icons) (required): 

http://prntscr.com/j9srox

### Screenshot of the console (press `F12` to bring up the console) (required): 

http://prntscr.com/j9srvv

### Explain what was not right (optional if obvious): 
The website added a new anti-ad blocker, preventing videos from loading if you have an ad blocker extension.

### Reproduction steps (optional if trivial): 
Play random video to see the message "Please disable AdBlock then try again. If you want to watch anime in high quality without ads, just get a subscription in premium anime site. Thanks for your supporting!"

### Environment (Required): 

- Operating System and Version: Windows 10 version 1709
- Browser and Version: Chrome (latest)
- Adblocker and Version: uBlock Origin + Nano Defender (both latest)

#### Your filter lists (Required): 

Default + Nanodefender filter lists

**Comment by jspenguin2017** [comment]
@okiehsch They seems to be back at it again...

**Comment by xnieatx** [comment]
A new update to uBlock Origin (1.16.2) was released today, and it seems to have fixed this issue. Thank you

**Comment by okiehsch** [comment]
If you still have issues after updating `uBO-filters`, there is the caveat I mentioned [here](https://github.com/uBlockOrigin/uAssets/issues/605#issuecomment-384199578). 
I have not found a way to work around that.

**Comment by jspenguin2017** [comment]
That's a big caveat. I'll look into it, did you pin down the offending script?

**Comment by jspenguin2017** [comment]
OK, all we need is to fool jQuery into believing `.widget.crop` is taller than 5 pixels. 
![image](https://user-images.githubusercontent.com/7283682/39274124-3ad24488-489e-11e8-906a-67c311aa4e23.png)

**Comment by jspenguin2017** [comment]
Alright, good enough for now.

**Comment by okiehsch** [comment]
Thanks, you are correct, I will add
`9anime.*###sidebar > .text-center.crop.widget:style(height: 5px !important)`
fixes the issue properly on my end.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/b035d8bc0e7af5848e0e82c062c412b164fd33ba

**Comment by InverIrisGlaive** [comment]
So I supposed this issue is now resolved using nano adblocker and nano defender as well? or only on ubo?

**Comment by jspenguin2017** [comment]
It's solved in uBO.

**Comment by InverIrisGlaive** [comment]
Guess I'll switch over to using uBO with nano-adblock until this issue is resolved

**Comment by jspenguin2017** [comment]
It is resolved, you just need to update the filters.

**Comment by InverIrisGlaive** [comment]
Thank you so much!

**Comment by InverIrisGlaive** [comment]
hmm still not working on my end, guess I'll just have to wait until it auto-update, as the update option didn't seem clickable on my end
![image](https://user-images.githubusercontent.com/38737968/39276702-b165ade8-48c0-11e8-92e2-0d9c23bc7b3b.png)

**Comment by jspenguin2017** [comment]
You need to flush your cache.

**Comment by zircher90** [comment]
It started happening again today.

**Comment by jspenguin2017** [comment]
@okiehsch Yep, guess what is broken again...

**Comment by okiehsch** [comment]
Hm, works on my end.

**Comment by okiehsch** [comment]
mapx- has added a commit today https://github.com/uBlockOrigin/uAssets/commit/d28018ce0617e7bf7fdc2824b2282eb079e1429f, have you updated your filter list?

**Comment by jspenguin2017** [comment]
I'll un-revert my patch, I'm not sure what happened last night, are they starting a cat and mouse game?

**Comment by okiehsch** [comment]
I still can't reproduce, so I am not sure what you mean.
 
https://github.com/uBlockOrigin/uAssets/commit/d28018ce0617e7bf7fdc2824b2282eb079e1429f fixed the anti-adblock message but also broke some site functionality, so it was changed https://github.com/uBlockOrigin/uAssets/commit/5ab918d6cd5be5acda57cff82ad6113afbc35ff7

This works on my end and I do not see any obvious site breakage.

**Comment by okiehsch** [comment]
By the way the reason the new filters were necessary was that they changed

> OK, all we need is to fool jQuery into believing .widget.crop is taller than 5 pixels.

It is now: "OK, all we need is to fool jQuery into believing .widget.crop is taller than **6** pixels."

**Comment by jspenguin2017** [comment]
Yea, I saw that style filter change, in a few days it'll be 10 pixels. I'll just remove those elements.

**Comment by okiehsch** [comment]
ThesetTimeout` filter already fixes the issue, I only changed the pixel filter, because of https://github.com/uBlockOrigin/uAssets/issues/2334#issuecomment-390631723

**Comment by okiehsch** [comment]
@jspenguin2017 they changed it up again, should not work for you now.

`https://www4.9anime.is/watch/pastel-life.lq36/m8qnwp`

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/c88dea10fd2d5e32343e56a0a58483738c8fb1f6
